name = "cool-cell-c75e"
main = "cloudflare-worker.js"
compatibility_date = "2024-01-01"

[vars]
ORIGIN_HOSTNAME = "main--allaboutv2--ddttom.aem.live"
PUSH_INVALIDATION = "enabled"

[[routes]]
pattern = "allabout.network/*"
zone_name = "allabout.network"

[[routes]]
pattern = "www.allabout.network/*"
zone_name = "allabout.network"
